services:
  - type: web
    name: pdf-diff-tool
    env: python
    region: oregon        # you can change region if needed
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11





